language: android
dist: trusty
android:
  components:
    - platform-tools
    - tools

script:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "build-tools;28.0.3"
    - ./gradlew test jacocoTestReport coveralls
