name: Deploy release

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set version
        run: |
          sed -i 's/$version/${{ steps.get_version.outputs.VERSION }}/g' app/version.properties

      - name: Get VCODE_TIME
        id: get_vcode_time
        run: echo ::set-output name=VCODE_TIME::$(date +%s)

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace -Dversion.code.time=${{ steps.get_vcode_time.outputs.VCODE_TIME }} -Dpurchase.validation.key=${{ secrets.PURCHASE_VALIDATION_KEY }}

      - name: Build AAB
        run: bash ./gradlew :app:bundleRelease --stacktrace -Dversion.code.time=${{ steps.get_vcode_time.outputs.VCODE_TIME }} -Dpurchase.validation.key=${{ secrets.PURCHASE_VALIDATION_KEY }}

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - uses: r0adkll/sign-android-release@v1
        name: Sign app AAB
        id: sign_app_aab
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK Release Asset
        id: upload-release-asset-apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{steps.sign_app_apk.outputs.signedReleaseFile}}
          asset_name: app-release.apk
          asset_content_type: application/zip

      - name: Choose Release track
        id: get_track
        run: echo ::set-output name=TRACK::$(if [[ "${{ steps.get_release.outputs.prerelease }}" == "false" ]] ; then echo production ; else echo alpha ; fi)

      - name: Upload AAB Google Play
        id: upload-release-asset-aab
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT }}
          packageName: com.github.frimtec.android.pikettassist
          releaseFiles: ${{steps.sign_app_aab.outputs.signedReleaseFile}}
          track: ${{ steps.get_track.outputs.TRACK }}
          whatsNewDirectory: google-play/whatsnew